name: "Release MagCat Source"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
   workflow_dispatch:
   schedule:
     - cron: '0 */4 * * *'
#  push:
#    branches:
#      - main
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      has_new_commits: ${{ steps.check_commits.outputs.has_new_commits }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for new commits
        id: check_commits
        run: |
          git fetch origin main
          if [ "$(git rev-list --count HEAD..origin/main)" -eq 0 ]; then
            echo "No new commits found."
            echo "has_new_commits=false" >> $GITHUB_OUTPUT
          else
            echo "New commits found."
            echo "has_new_commits=true" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check
    if: needs.check.outputs.has_new_commits == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "MagCat Action"
          git config --global user.email "action@magcat.app"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.10.0

      - name: Git commit hash
        uses: prompt/actions-commit-hash@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      - name: Build the source
        run: |
          pnpm run build
          echo "TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Tag
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: dist/**

      - name: Release Latest
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: dist/**
